import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="h-screen overflow-auto bg-zinc-950 max-md:p-4">
        <div className="h-full max-h-screen">
          <Header />
          <div className="h-[calc(100%-4.25rem)]">{children}</div>
        </div>
      </body>
    </html>
  )
}
